#!/usr/bin/env python3
"""
spr_gen.py — ASCII-art -> packed 1-bit sprite C arrays for ssd1306_blit() (M-UI-1).

Emits the SAME packing the blit core (src/ssd1306/ssd1306_blit_impl.h) and draw_pixel expect:
column-major page-rows, byte = spr[col + w*(row>>3)], bit (row&7), bit0 = topmost pixel, 1 = lit.
ASCII art is more reviewable in a diff than a binary PNG, and needs no image library.

Source format (a .spr text file; see src/ssd1306/sprites.spr):
    ; lines starting with ';' are comments
    @sprite ghost_possess          ; begins a sprite named ghost_possess
    .######.                       ; pixel rows: lit = any of  # X x * @ 1 O ,  off = anything else
    ########                       ; rows may be ragged; width = the longest row, short rows pad with off
    @end                           ; optional; a new @sprite or EOF also ends one

Usage:
    tools/spr_gen.py src/ssd1306/sprites.spr -o src/ssd1306/sprites.gen.h
    tools/spr_gen.py src/ssd1306/sprites.spr            # -> stdout

The generated header is committed (no build-time dependency on Python). Re-run when art changes.
"""
import argparse
import sys

LIT = set("#Xx*@1O")


def pack(rows):
    """rows: list[str] -> (width, height, bytes[]) in the column-major page-row packing."""
    h = len(rows)
    w = max((len(r) for r in rows), default=0)
    pages = (h + 7) // 8
    out = []
    for p in range(pages):
        for col in range(w):
            byte = 0
            for b in range(8):
                row = p * 8 + b
                if row < h and col < len(rows[row]) and rows[row][col] in LIT:
                    byte |= (1 << b)
            out.append(byte)
    return w, h, out


def parse(text):
    """-> list[(name, rows)] preserving file order."""
    sprites, name, rows = [], None, []
    for raw in text.splitlines():
        line = raw.rstrip("\n")
        s = line.strip()
        if s.startswith(";"):
            continue
        if s.startswith("@sprite"):
            if name is not None:
                sprites.append((name, rows))
            parts = s.split()
            if len(parts) < 2:
                sys.exit("error: @sprite needs a name")
            name, rows = parts[1], []
        elif s.startswith("@end"):
            if name is not None:
                sprites.append((name, rows))
            name, rows = None, []
        elif name is not None:
            rows.append(line)  # keep original (un-stripped) so leading spaces = off pixels
    if name is not None:
        sprites.append((name, rows))
    return sprites


def emit(sprites):
    lines = [
        "/* GENERATED by tools/spr_gen.py from sprites.spr — DO NOT EDIT BY HAND. */",
        "/* Packing matches ssd1306_blit_impl.h: spr[col + w*(row>>3)], bit (row&7), bit0=top, 1=lit. */",
        "#ifndef HG_SPRITES_GEN_H",
        "#define HG_SPRITES_GEN_H",
        "#include <stdint.h>",
        "",
    ]
    for name, rows in sprites:
        if not rows:
            sys.exit(f"error: sprite '{name}' has no pixel rows")
        w, h, data = pack(rows)
        body = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"#define {name}_W {w}")
        lines.append(f"#define {name}_H {h}")
        lines.append(f"static const uint8_t {name}[] = {{ {body} }};  /* {w}x{h}, {len(data)} B */")
        lines.append("")
    lines.append("#endif // HG_SPRITES_GEN_H")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="ASCII-art -> packed 1-bit sprite C arrays")
    ap.add_argument("source", help=".spr ASCII-art source file")
    ap.add_argument("-o", "--out", help="output .h (default: stdout)")
    args = ap.parse_args()
    with open(args.source) as f:
        sprites = parse(f.read())
    if not sprites:
        sys.exit("error: no sprites found")
    out = emit(sprites)
    if args.out:
        with open(args.out, "w") as f:
            f.write(out)
        print(f"wrote {len(sprites)} sprite(s) -> {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main()
